/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_ThreadsJNI */

#ifndef _Included_org_wpilib_hardware_hal_ThreadsJNI
#define _Included_org_wpilib_hardware_hal_ThreadsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_ThreadsJNI
 * Method:    getCurrentThreadPriority
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_ThreadsJNI_getCurrentThreadPriority
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_ThreadsJNI
 * Method:    setCurrentThreadPriority
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_ThreadsJNI_setCurrentThreadPriority
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
