/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_DriverStationJNI */

#ifndef _Included_org_wpilib_hardware_hal_DriverStationJNI
#define _Included_org_wpilib_hardware_hal_DriverStationJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_UNKNOWN
#define org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_UNKNOWN 0L
#undef org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_RED_1
#define org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_RED_1 1L
#undef org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_RED_2
#define org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_RED_2 2L
#undef org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_RED_3
#define org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_RED_3 3L
#undef org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_BLUE_1
#define org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_BLUE_1 4L
#undef org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_BLUE_2
#define org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_BLUE_2 5L
#undef org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_BLUE_3
#define org_wpilib_hardware_hal_DriverStationJNI_ALLIANCE_STATION_BLUE_3 6L
#undef org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_AXES
#define org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_AXES 12L
#undef org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_BUTTONS
#define org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_BUTTONS 64L
#undef org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_POVS
#define org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_POVS 8L
#undef org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICKS
#define org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICKS 6L
#undef org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_TOUCHPADS
#define org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_TOUCHPADS 2L
#undef org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_TOUCHPAD_FINGERS
#define org_wpilib_hardware_hal_DriverStationJNI_MAX_JOYSTICK_TOUCHPAD_FINGERS 2L
/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    observeUserProgramStarting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_observeUserProgramStarting
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    observeUserProgram
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_observeUserProgram
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    nativeGetControlWord
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_nativeGetControlWord
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    nativeGetUncachedControlWord
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_nativeGetUncachedControlWord
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    setOpModeOptions
 * Signature: ([Lorg/wpilib/hardware/hal/OpModeOption;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_setOpModeOptions
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    nativeGetAllianceStation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_nativeGetAllianceStation
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getAllJoystickData
 * Signature: (I[F[S[B[F[J)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getAllJoystickData
  (JNIEnv *, jclass, jint, jfloatArray, jshortArray, jbyteArray, jfloatArray, jlongArray);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    setJoystickRumble
 * Signature: (BIIII)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_setJoystickRumble
  (JNIEnv *, jclass, jbyte, jint, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    setJoystickLeds
 * Signature: (BI)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_setJoystickLeds
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getJoystickIsGamepad
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getJoystickIsGamepad
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getJoystickGamepadType
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getJoystickGamepadType
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getJoystickSupportedOutputs
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getJoystickSupportedOutputs
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getJoystickName
 * Signature: (B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getJoystickName
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getMatchTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getMatchTime
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getMatchInfo
 * Signature: (Lorg/wpilib/hardware/hal/MatchInfoData;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getMatchInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getGameData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getGameData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    sendError
 * Signature: (ZILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_sendError
  (JNIEnv *, jclass, jboolean, jint, jstring, jstring, jstring, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    sendConsoleLine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_sendConsoleLine
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    sendProgramCrash
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_sendProgramCrash
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    refreshDSData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_refreshDSData
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    provideNewDataEventHandle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_provideNewDataEventHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    removeNewDataEventHandle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_removeNewDataEventHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    getOutputsActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_getOutputsActive
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DriverStationJNI
 * Method:    writeDisplayAnsi
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DriverStationJNI_writeDisplayAnsi
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
