/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_SimDeviceJNI */

#ifndef _Included_org_wpilib_hardware_hal_SimDeviceJNI
#define _Included_org_wpilib_hardware_hal_SimDeviceJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_wpilib_hardware_hal_SimDeviceJNI_VALUE_INPUT
#define org_wpilib_hardware_hal_SimDeviceJNI_VALUE_INPUT 0L
#undef org_wpilib_hardware_hal_SimDeviceJNI_VALUE_OUTPUT
#define org_wpilib_hardware_hal_SimDeviceJNI_VALUE_OUTPUT 1L
#undef org_wpilib_hardware_hal_SimDeviceJNI_VALUE_BIDIR
#define org_wpilib_hardware_hal_SimDeviceJNI_VALUE_BIDIR 2L
/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    createSimDevice
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_createSimDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    freeSimDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_freeSimDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    getSimDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_getSimDeviceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    createSimValueNative
 * Signature: (ILjava/lang/String;IIJD)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_createSimValueNative
  (JNIEnv *, jclass, jint, jstring, jint, jint, jlong, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    createSimValueEnum
 * Signature: (ILjava/lang/String;I[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_createSimValueEnum
  (JNIEnv *, jclass, jint, jstring, jint, jobjectArray, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    createSimValueEnumDouble
 * Signature: (ILjava/lang/String;I[Ljava/lang/String;[DI)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_createSimValueEnumDouble
  (JNIEnv *, jclass, jint, jstring, jint, jobjectArray, jdoubleArray, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    getSimValue
 * Signature: (I)Lorg/wpilib/hardware/hal/HALValue;
 */
JNIEXPORT jobject JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_getSimValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    getSimValueInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_getSimValueInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    getSimValueLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_getSimValueLong
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    getSimValueDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_getSimValueDouble
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    getSimValueEnum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_getSimValueEnum
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    getSimValueBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_getSimValueBoolean
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    setSimValueNative
 * Signature: (IIJD)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_setSimValueNative
  (JNIEnv *, jclass, jint, jint, jlong, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_SimDeviceJNI
 * Method:    resetSimValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SimDeviceJNI_resetSimValue
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
