/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_REVPHJNI */

#ifndef _Included_org_wpilib_hardware_hal_REVPHJNI
#define _Included_org_wpilib_hardware_hal_REVPHJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_wpilib_hardware_hal_REVPHJNI_COMPRESSOR_CONFIG_TYPE_DISABLED
#define org_wpilib_hardware_hal_REVPHJNI_COMPRESSOR_CONFIG_TYPE_DISABLED 0L
#undef org_wpilib_hardware_hal_REVPHJNI_COMPRESSOR_CONFIG_TYPE_DIGITAL
#define org_wpilib_hardware_hal_REVPHJNI_COMPRESSOR_CONFIG_TYPE_DIGITAL 1L
#undef org_wpilib_hardware_hal_REVPHJNI_COMPRESSOR_CONFIG_TYPE_ANALOG
#define org_wpilib_hardware_hal_REVPHJNI_COMPRESSOR_CONFIG_TYPE_ANALOG 2L
#undef org_wpilib_hardware_hal_REVPHJNI_COMPRESSOR_CONFIG_TYPE_HYBRID
#define org_wpilib_hardware_hal_REVPHJNI_COMPRESSOR_CONFIG_TYPE_HYBRID 3L
/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    initialize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    checkSolenoidChannel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_checkSolenoidChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getCompressor
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getCompressor
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    setCompressorConfig
 * Signature: (IDDZZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_setCompressorConfig
  (JNIEnv *, jclass, jint, jdouble, jdouble, jboolean, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    setClosedLoopControlDisabled
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_setClosedLoopControlDisabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    setClosedLoopControlDigital
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_setClosedLoopControlDigital
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    setClosedLoopControlAnalog
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_setClosedLoopControlAnalog
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    setClosedLoopControlHybrid
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_setClosedLoopControlHybrid
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getCompressorConfig
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getCompressorConfig
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getPressureSwitch
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getPressureSwitch
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getAnalogVoltage
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getAnalogVoltage
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getCompressorCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getCompressorCurrent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getSolenoids
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getSolenoids
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    setSolenoids
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_setSolenoids
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    fireOneShot
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_fireOneShot
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    clearStickyFaults
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_clearStickyFaults
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getInputVoltage
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getInputVoltage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    get5VVoltage
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_get5VVoltage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getSolenoidCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getSolenoidCurrent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getSolenoidVoltage
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getSolenoidVoltage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getStickyFaultsNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getStickyFaultsNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getFaultsNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getFaultsNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getSolenoidDisabledList
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getSolenoidDisabledList
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_REVPHJNI
 * Method:    getVersion
 * Signature: (I)Lorg/wpilib/hardware/hal/REVPHVersion;
 */
JNIEXPORT jobject JNICALL Java_org_wpilib_hardware_hal_REVPHJNI_getVersion
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
