/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_HALUtil */

#ifndef _Included_org_wpilib_hardware_hal_HALUtil
#define _Included_org_wpilib_hardware_hal_HALUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef org_wpilib_hardware_hal_HALUtil_NULL_PARAMETER
#define org_wpilib_hardware_hal_HALUtil_NULL_PARAMETER -1005L
#undef org_wpilib_hardware_hal_HALUtil_VOLTAGE_OUT_OF_RANGE
#define org_wpilib_hardware_hal_HALUtil_VOLTAGE_OUT_OF_RANGE 1002L
#undef org_wpilib_hardware_hal_HALUtil_INCOMPATIBLE_STATE
#define org_wpilib_hardware_hal_HALUtil_INCOMPATIBLE_STATE 1015L
#undef org_wpilib_hardware_hal_HALUtil_NO_AVAILABLE_RESOURCES
#define org_wpilib_hardware_hal_HALUtil_NO_AVAILABLE_RESOURCES -1004L
#undef org_wpilib_hardware_hal_HALUtil_PARAMETER_OUT_OF_RANGE
#define org_wpilib_hardware_hal_HALUtil_PARAMETER_OUT_OF_RANGE -1028L
#undef org_wpilib_hardware_hal_HALUtil_RUNTIME_SYSTEMCORE
#define org_wpilib_hardware_hal_HALUtil_RUNTIME_SYSTEMCORE 0L
#undef org_wpilib_hardware_hal_HALUtil_RUNTIME_SIMULATION
#define org_wpilib_hardware_hal_HALUtil_RUNTIME_SIMULATION 1L
/*
 * Class:     org_wpilib_hardware_hal_HALUtil
 * Method:    getSerialNumber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_HALUtil_getSerialNumber
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HALUtil
 * Method:    getComments
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_HALUtil_getComments
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HALUtil
 * Method:    getTeamNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_HALUtil_getTeamNumber
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HALUtil
 * Method:    getMonotonicTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wpilib_hardware_hal_HALUtil_getMonotonicTime
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HALUtil
 * Method:    getHALRuntimeType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_HALUtil_getHALRuntimeType
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HALUtil
 * Method:    getHALErrorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_HALUtil_getHALErrorMessage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_HALUtil
 * Method:    getHALErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_HALUtil_getHALErrno
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HALUtil
 * Method:    getHALstrerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_HALUtil_getHALstrerror
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
