/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_AnalogInputJNI */

#ifndef _Included_org_wpilib_hardware_hal_AnalogInputJNI
#define _Included_org_wpilib_hardware_hal_AnalogInputJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    initializeAnalogInputPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_initializeAnalogInputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    freeAnalogInputPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_freeAnalogInputPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    checkAnalogModule
 * Signature: (B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_checkAnalogModule
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    checkAnalogInputChannel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_checkAnalogInputChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    setAnalogInputSimDevice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_setAnalogInputSimDevice
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    getAnalogValue
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_getAnalogValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    getAnalogVoltsToValue
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_getAnalogVoltsToValue
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    getAnalogValueToVolts
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_getAnalogValueToVolts
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_AnalogInputJNI
 * Method:    getAnalogVoltage
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_AnalogInputJNI_getAnalogVoltage
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
