/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_IMUJNI */

#ifndef _Included_org_wpilib_hardware_hal_IMUJNI
#define _Included_org_wpilib_hardware_hal_IMUJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUAcceleration
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUAcceleration
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUGyroRates
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUGyroRates
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUEulerAnglesFlat
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUEulerAnglesFlat
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUEulerAnglesLandscape
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUEulerAnglesLandscape
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUEulerAnglesPortrait
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUEulerAnglesPortrait
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUQuaternion
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUQuaternion
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUYawFlat
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUYawFlat
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUYawLandscape
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUYawLandscape
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_IMUJNI
 * Method:    getIMUYawPortrait
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_IMUJNI_getIMUYawPortrait
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
