/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_SimDeviceDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    setSimDeviceEnabled
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_setSimDeviceEnabled
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    isSimDeviceEnabled
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_isSimDeviceEnabled
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    registerSimDeviceCreatedCallback
 * Signature: (Ljava/lang/String;Lorg/wpilib/hardware/hal/simulation/SimDeviceCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_registerSimDeviceCreatedCallback
  (JNIEnv *, jclass, jstring, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    cancelSimDeviceCreatedCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_cancelSimDeviceCreatedCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    registerSimDeviceFreedCallback
 * Signature: (Ljava/lang/String;Lorg/wpilib/hardware/hal/simulation/SimDeviceCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_registerSimDeviceFreedCallback
  (JNIEnv *, jclass, jstring, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    cancelSimDeviceFreedCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_cancelSimDeviceFreedCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    getSimDeviceHandle
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_getSimDeviceHandle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    getSimDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_getSimDeviceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    getSimValueDeviceHandle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_getSimValueDeviceHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    enumerateSimDevices
 * Signature: (Ljava/lang/String;)[Lorg/wpilib/hardware/hal/simulation/SimDeviceDataJNI/SimDeviceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_enumerateSimDevices
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    registerSimValueCreatedCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/SimValueCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_registerSimValueCreatedCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    cancelSimValueCreatedCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_cancelSimValueCreatedCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    registerSimValueChangedCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/SimValueCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_registerSimValueChangedCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    cancelSimValueChangedCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_cancelSimValueChangedCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    registerSimValueResetCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/SimValueCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_registerSimValueResetCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    cancelSimValueResetCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_cancelSimValueResetCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    getSimValueHandle
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_getSimValueHandle
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    enumerateSimValues
 * Signature: (I)[Lorg/wpilib/hardware/hal/simulation/SimDeviceDataJNI/SimValueInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_enumerateSimValues
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    getSimValueEnumOptions
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_getSimValueEnumOptions
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    getSimValueEnumDoubleValues
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_getSimValueEnumDoubleValues
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimDeviceDataJNI
 * Method:    resetSimDeviceData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimDeviceDataJNI_resetSimDeviceData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
