/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_UsageReportingJNI */

#ifndef _Included_org_wpilib_hardware_hal_UsageReportingJNI
#define _Included_org_wpilib_hardware_hal_UsageReportingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_UsageReportingJNI
 * Method:    report
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_UsageReportingJNI_report
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_wpilib_hardware_hal_UsageReportingJNI
 * Method:    publishCanVersion
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_UsageReportingJNI_publishCanVersion
  (JNIEnv *, jclass, jint, jint, jstring, jstring);

/*
 * Class:     org_wpilib_hardware_hal_UsageReportingJNI
 * Method:    publishVersion
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_UsageReportingJNI_publishVersion
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_wpilib_hardware_hal_UsageReportingJNI
 * Method:    publishWpilibVersion
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_UsageReportingJNI_publishWpilibVersion
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
