/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_SystemServerJNI */

#ifndef _Included_org_wpilib_hardware_hal_SystemServerJNI
#define _Included_org_wpilib_hardware_hal_SystemServerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_SystemServerJNI
 * Method:    getSystemServerHandle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SystemServerJNI_getSystemServerHandle
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
