/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_EncoderJNI */

#ifndef _Included_org_wpilib_hardware_hal_EncoderJNI
#define _Included_org_wpilib_hardware_hal_EncoderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    initializeEncoder
 * Signature: (IIZI)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_initializeEncoder
  (JNIEnv *, jclass, jint, jint, jboolean, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    freeEncoder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_freeEncoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    setEncoderSimDevice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_setEncoderSimDevice
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderRaw
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderRaw
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncodingScaleFactor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncodingScaleFactor
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    resetEncoder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_resetEncoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderStopped
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderStopped
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderDirection
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderDirection
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderDistance
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderDistance
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderRate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderRate
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    setEncoderRateWindow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_setEncoderRateWindow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    setEncoderDistancePerPulse
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_setEncoderDistancePerPulse
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    setEncoderReverseDirection
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_setEncoderReverseDirection
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderFPGAIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderFPGAIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderEncodingScale
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderEncodingScale
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderDecodingScaleFactor
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderDecodingScaleFactor
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderDistancePerPulse
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderDistancePerPulse
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_EncoderJNI
 * Method:    getEncoderEncodingType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_EncoderJNI_getEncoderEncodingType
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
