/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_CounterJNI */

#ifndef _Included_org_wpilib_hardware_hal_CounterJNI
#define _Included_org_wpilib_hardware_hal_CounterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_CounterJNI
 * Method:    initializeCounter
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CounterJNI_initializeCounter
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_CounterJNI
 * Method:    freeCounter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CounterJNI_freeCounter
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CounterJNI
 * Method:    setCounterEdgeConfiguration
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CounterJNI_setCounterEdgeConfiguration
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_CounterJNI
 * Method:    setCounterRateWindow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CounterJNI_setCounterRateWindow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CounterJNI
 * Method:    resetCounter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CounterJNI_resetCounter
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CounterJNI
 * Method:    getCounter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CounterJNI_getCounter
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CounterJNI
 * Method:    getCounterRate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_CounterJNI_getCounterRate
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CounterJNI
 * Method:    getCounterStopped
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CounterJNI_getCounterStopped
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
