/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_HAL */

#ifndef _Included_org_wpilib_hardware_hal_HAL
#define _Included_org_wpilib_hardware_hal_HAL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_HAL_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_HAL_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    hasMain
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_HAL_hasMain
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    runMain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_HAL_runMain
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    exitMain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_HAL_exitMain
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_HAL_terminate
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    simPeriodicBeforeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_HAL_simPeriodicBeforeNative
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    simPeriodicAfterNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_HAL_simPeriodicAfterNative
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    getBrownedOut
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_HAL_getBrownedOut
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    getSystemActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_HAL_getSystemActive
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    getRSLState
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_HAL_getRSLState
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    getCommsDisableCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_HAL_getCommsDisableCount
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_HAL
 * Method:    getSystemTimeValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_HAL_getSystemTimeValid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
