/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_NotifierDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_NotifierDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_NotifierDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_NotifierDataJNI
 * Method:    getNextTimeout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wpilib_hardware_hal_simulation_NotifierDataJNI_getNextTimeout
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_NotifierDataJNI
 * Method:    getNumNotifiers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_NotifierDataJNI_getNumNotifiers
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
