/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_can_CANJNI */

#ifndef _Included_org_wpilib_hardware_hal_can_CANJNI
#define _Included_org_wpilib_hardware_hal_can_CANJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_wpilib_hardware_hal_can_CANJNI_CAN_SEND_PERIOD_NO_REPEAT
#define org_wpilib_hardware_hal_can_CANJNI_CAN_SEND_PERIOD_NO_REPEAT 0L
#undef org_wpilib_hardware_hal_can_CANJNI_CAN_SEND_PERIOD_STOP_REPEATING
#define org_wpilib_hardware_hal_can_CANJNI_CAN_SEND_PERIOD_STOP_REPEATING -1L
#undef org_wpilib_hardware_hal_can_CANJNI_CAN_IS_FRAME_REMOTE
#define org_wpilib_hardware_hal_can_CANJNI_CAN_IS_FRAME_REMOTE 1073741824L
#undef org_wpilib_hardware_hal_can_CANJNI_CAN_IS_FRAME_11BIT
#define org_wpilib_hardware_hal_can_CANJNI_CAN_IS_FRAME_11BIT -2147483648L
/*
 * Class:     org_wpilib_hardware_hal_can_CANJNI
 * Method:    sendMessage
 * Signature: (II[BIII)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_can_CANJNI_sendMessage
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_can_CANJNI
 * Method:    receiveMessage
 * Signature: (IILorg/wpilib/hardware/hal/can/CANReceiveMessage;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_can_CANJNI_receiveMessage
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_wpilib_hardware_hal_can_CANJNI
 * Method:    getCANStatus
 * Signature: (ILorg/wpilib/hardware/hal/can/CANStatus;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_can_CANJNI_getCANStatus
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_wpilib_hardware_hal_can_CANJNI
 * Method:    openCANStreamSession
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_can_CANJNI_openCANStreamSession
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_can_CANJNI
 * Method:    closeCANStreamSession
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_can_CANJNI_closeCANStreamSession
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_can_CANJNI
 * Method:    readCANStreamSession
 * Signature: (I[Lorg/wpilib/hardware/hal/can/CANStreamMessage;I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_can_CANJNI_readCANStreamSession
  (JNIEnv *, jclass, jint, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
