/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    registerInitializedCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_registerInitializedCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    cancelInitializedCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_cancelInitializedCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    getInitialized
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_getInitialized
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    setInitialized
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_setInitialized
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    registerTemperatureCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_registerTemperatureCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    cancelTemperatureCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_cancelTemperatureCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    getTemperature
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_getTemperature
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    setTemperature
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_setTemperature
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    registerVoltageCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_registerVoltageCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    cancelVoltageCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_cancelVoltageCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    getVoltage
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_getVoltage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    setVoltage
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_setVoltage
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    registerCurrentCallback
 * Signature: (IILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_registerCurrentCallback
  (JNIEnv *, jclass, jint, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    cancelCurrentCallback
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_cancelCurrentCallback
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    getCurrent
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_getCurrent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    setCurrent
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_setCurrent
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI
 * Method:    resetData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_PowerDistributionDataJNI_resetData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
