/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_NotifierJNI */

#ifndef _Included_org_wpilib_hardware_hal_NotifierJNI
#define _Included_org_wpilib_hardware_hal_NotifierJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_NotifierJNI
 * Method:    createNotifier
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_NotifierJNI_createNotifier
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_NotifierJNI
 * Method:    setNotifierName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_NotifierJNI_setNotifierName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_wpilib_hardware_hal_NotifierJNI
 * Method:    destroyNotifier
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_NotifierJNI_destroyNotifier
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_NotifierJNI
 * Method:    setNotifierAlarm
 * Signature: (IJJZZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_NotifierJNI_setNotifierAlarm
  (JNIEnv *, jclass, jint, jlong, jlong, jboolean, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_NotifierJNI
 * Method:    cancelNotifierAlarm
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_NotifierJNI_cancelNotifierAlarm
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_NotifierJNI
 * Method:    acknowledgeNotifierAlarm
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_NotifierJNI_acknowledgeNotifierAlarm
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_NotifierJNI
 * Method:    getNotifierOverrun
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_NotifierJNI_getNotifierOverrun
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
