/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_DriverStationDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_DriverStationDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_DriverStationDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerEnabledCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerEnabledCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelEnabledCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelEnabledCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getEnabled
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerRobotModeCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerRobotModeCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelRobotModeCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelRobotModeCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    nativeGetRobotMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_nativeGetRobotMode
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    nativeSetRobotMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_nativeSetRobotMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerEStopCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerEStopCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelEStopCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelEStopCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getEStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getEStop
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setEStop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setEStop
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerFmsAttachedCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerFmsAttachedCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelFmsAttachedCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelFmsAttachedCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getFmsAttached
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getFmsAttached
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setFmsAttached
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setFmsAttached
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerDsAttachedCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerDsAttachedCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelDsAttachedCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelDsAttachedCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getDsAttached
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getDsAttached
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setDsAttached
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setDsAttached
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerAllianceStationIdCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerAllianceStationIdCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelAllianceStationIdCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelAllianceStationIdCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getAllianceStationId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getAllianceStationId
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setAllianceStationId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setAllianceStationId
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerMatchTimeCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerMatchTimeCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelMatchTimeCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelMatchTimeCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getMatchTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getMatchTime
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setMatchTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setMatchTime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerOpModeCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerOpModeCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelOpModeCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelOpModeCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getOpMode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getOpMode
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setOpMode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setOpMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerOpModeOptionsCallback
 * Signature: (Ljava/util/function/BiConsumer;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerOpModeOptionsCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    cancelOpModeOptionsCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_cancelOpModeOptionsCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getOpModeOptions
 * Signature: ()[Lorg/wpilib/hardware/hal/OpModeOption;
 */
JNIEXPORT jobjectArray JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getOpModeOptions
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickAxes
 * Signature: (B[FS)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickAxes
  (JNIEnv *, jclass, jbyte, jfloatArray, jshort);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickPOVs
 * Signature: (B[BS)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickPOVs
  (JNIEnv *, jclass, jbyte, jbyteArray, jshort);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickButtons
 * Signature: (BJJ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickButtons
  (JNIEnv *, jclass, jbyte, jlong, jlong);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getJoystickLeds
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getJoystickLeds
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    getJoystickRumble
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_getJoystickRumble
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setMatchInfo
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setMatchInfo
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setGameData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setGameData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    registerAllCallbacks
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_registerAllCallbacks
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    notifyNewData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_notifyNewData
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setSendError
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setSendError
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setSendConsoleLine
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setSendConsoleLine
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickButton
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickButton
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickAxis
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickAxis
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickPOV
 * Signature: (IIB)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickPOV
  (JNIEnv *, jclass, jint, jint, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickButtonsValue
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickButtonsValue
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickAxesAvailable
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickAxesAvailable
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickPOVsAvailable
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickPOVsAvailable
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickButtonsAvailable
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickButtonsAvailable
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setTouchpadCounts
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setTouchpadCounts
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setTouchpadFinger
 * Signature: (IIIZFF)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setTouchpadFinger
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloat, jfloat);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickIsGamepad
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickIsGamepad
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickGamepadType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickGamepadType
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setJoystickSupportedOutputs
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setJoystickSupportedOutputs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setEventName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setEventName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setMatchType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setMatchType
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setMatchNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setMatchNumber
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    setReplayNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_setReplayNumber
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DriverStationDataJNI
 * Method:    resetData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DriverStationDataJNI_resetData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
