/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_CTREPCMJNI */

#ifndef _Included_org_wpilib_hardware_hal_CTREPCMJNI
#define _Included_org_wpilib_hardware_hal_CTREPCMJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    initialize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    checkSolenoidChannel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_checkSolenoidChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getCompressor
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getCompressor
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    setClosedLoopControl
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_setClosedLoopControl
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getClosedLoopControl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getClosedLoopControl
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getPressureSwitch
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getPressureSwitch
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getCompressorCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getCompressorCurrent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getCompressorCurrentTooHighFault
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getCompressorCurrentTooHighFault
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getCompressorCurrentTooHighStickyFault
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getCompressorCurrentTooHighStickyFault
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getCompressorShortedFault
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getCompressorShortedFault
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getCompressorShortedStickyFault
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getCompressorShortedStickyFault
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getCompressorNotConnectedFault
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getCompressorNotConnectedFault
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getCompressorNotConnectedStickyFault
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getCompressorNotConnectedStickyFault
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getSolenoids
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getSolenoids
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    setSolenoids
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_setSolenoids
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getSolenoidDisabledList
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getSolenoidDisabledList
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getSolenoidVoltageFault
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getSolenoidVoltageFault
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    getSolenoidVoltageStickyFault
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_getSolenoidVoltageStickyFault
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    clearAllStickyFaults
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_clearAllStickyFaults
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    fireOneShot
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_fireOneShot
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CTREPCMJNI
 * Method:    setOneShotDuration
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CTREPCMJNI_setOneShotDuration
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
