/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_RoboRioDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_RoboRioDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_RoboRioDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerVInVoltageCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerVInVoltageCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelVInVoltageCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelVInVoltageCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getVInVoltage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getVInVoltage
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setVInVoltage
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setVInVoltage
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerUserVoltage3V3Callback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerUserVoltage3V3Callback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelUserVoltage3V3Callback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelUserVoltage3V3Callback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getUserVoltage3V3
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getUserVoltage3V3
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setUserVoltage3V3
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setUserVoltage3V3
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerUserCurrent3V3Callback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerUserCurrent3V3Callback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelUserCurrent3V3Callback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelUserCurrent3V3Callback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getUserCurrent3V3
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getUserCurrent3V3
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setUserCurrent3V3
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setUserCurrent3V3
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerUserActive3V3Callback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerUserActive3V3Callback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelUserActive3V3Callback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelUserActive3V3Callback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getUserActive3V3
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getUserActive3V3
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setUserActive3V3
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setUserActive3V3
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerUserFaults3V3Callback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerUserFaults3V3Callback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelUserFaults3V3Callback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelUserFaults3V3Callback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getUserFaults3V3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getUserFaults3V3
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setUserFaults3V3
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setUserFaults3V3
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerBrownoutVoltageCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerBrownoutVoltageCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelBrownoutVoltageCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelBrownoutVoltageCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getBrownoutVoltage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getBrownoutVoltage
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setBrownoutVoltage
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setBrownoutVoltage
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerBrownoutRecoveryVoltageCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerBrownoutRecoveryVoltageCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelBrownoutRecoveryVoltageCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelBrownoutRecoveryVoltageCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getBrownoutRecoveryVoltage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getBrownoutRecoveryVoltage
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setBrownoutRecoveryVoltage
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setBrownoutRecoveryVoltage
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerCPUTempCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerCPUTempCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelCPUTempCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelCPUTempCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getCPUTemp
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getCPUTemp
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setCPUTemp
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setCPUTemp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    registerTeamNumberCallback
 * Signature: (Lorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_registerTeamNumberCallback
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    cancelTeamNumberCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_cancelTeamNumberCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getTeamNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getTeamNumber
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setTeamNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setTeamNumber
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getSerialNumber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getSerialNumber
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setSerialNumber
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setSerialNumber
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    getComments
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_getComments
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    setComments
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_setComments
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_wpilib_hardware_hal_simulation_RoboRioDataJNI
 * Method:    resetData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_RoboRioDataJNI_resetData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
