/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_PWMJNI */

#ifndef _Included_org_wpilib_hardware_hal_PWMJNI
#define _Included_org_wpilib_hardware_hal_PWMJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_PWMJNI
 * Method:    initializePWMPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PWMJNI_initializePWMPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PWMJNI
 * Method:    checkPWMChannel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_PWMJNI_checkPWMChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PWMJNI
 * Method:    freePWMPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PWMJNI_freePWMPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PWMJNI
 * Method:    setPWMSimDevice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PWMJNI_setPWMSimDevice
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_PWMJNI
 * Method:    setPulseTimeMicroseconds
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PWMJNI_setPulseTimeMicroseconds
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_PWMJNI
 * Method:    getPulseTimeMicroseconds
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PWMJNI_getPulseTimeMicroseconds
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PWMJNI
 * Method:    setPWMOutputPeriod
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PWMJNI_setPWMOutputPeriod
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
