/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_DutyCycleDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    registerInitializedCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_registerInitializedCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    cancelInitializedCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_cancelInitializedCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    getInitialized
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_getInitialized
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    setInitialized
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_setInitialized
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    registerFrequencyCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_registerFrequencyCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    cancelFrequencyCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_cancelFrequencyCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    getFrequency
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_getFrequency
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    setFrequency
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_setFrequency
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    registerOutputCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_registerOutputCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    cancelOutputCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_cancelOutputCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    getOutput
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_getOutput
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    setOutput
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_setOutput
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DutyCycleDataJNI
 * Method:    resetData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DutyCycleDataJNI_resetData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
