/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_PowerJNI */

#ifndef _Included_org_wpilib_hardware_hal_PowerJNI
#define _Included_org_wpilib_hardware_hal_PowerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    getVinVoltage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerJNI_getVinVoltage
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    getUserVoltage3V3
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerJNI_getUserVoltage3V3
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    getUserCurrent3V3
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerJNI_getUserCurrent3V3
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    setUserEnabled3V3
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PowerJNI_setUserEnabled3V3
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    getUserActive3V3
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_PowerJNI_getUserActive3V3
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    getUserCurrentFaults3V3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PowerJNI_getUserCurrentFaults3V3
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    resetUserCurrentFaults
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PowerJNI_resetUserCurrentFaults
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    setBrownoutVoltages
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PowerJNI_setBrownoutVoltages
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_PowerJNI
 * Method:    getCPUTemp
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerJNI_getCPUTemp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
