/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_I2CDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_I2CDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_I2CDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    registerInitializedCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_registerInitializedCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    cancelInitializedCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_cancelInitializedCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    getInitialized
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_getInitialized
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    setInitialized
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_setInitialized
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    registerReadCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/BufferCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_registerReadCallback
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    cancelReadCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_cancelReadCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    registerWriteCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/ConstBufferCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_registerWriteCallback
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    cancelWriteCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_cancelWriteCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_I2CDataJNI
 * Method:    resetData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_I2CDataJNI_resetData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
