/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_SerialPortJNI */

#ifndef _Included_org_wpilib_hardware_hal_SerialPortJNI
#define _Included_org_wpilib_hardware_hal_SerialPortJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialInitializePort
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialInitializePort
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialInitializePortDirect
 * Signature: (BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialInitializePortDirect
  (JNIEnv *, jclass, jbyte, jstring);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetBaudRate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetBaudRate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetDataBits
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetDataBits
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetParity
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetParity
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetStopBits
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetStopBits
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetWriteMode
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetWriteMode
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetFlowControl
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetFlowControl
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetTimeout
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetTimeout
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialEnableTermination
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialEnableTermination
  (JNIEnv *, jclass, jint, jchar);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialDisableTermination
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialDisableTermination
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetReadBufferSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetReadBufferSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialSetWriteBufferSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialSetWriteBufferSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialGetBytesReceived
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialGetBytesReceived
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialRead
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialRead
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialWrite
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialWrite
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialFlush
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialFlush
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_SerialPortJNI
 * Method:    serialClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_SerialPortJNI_serialClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
