/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_CANAPIJNI */

#ifndef _Included_org_wpilib_hardware_hal_CANAPIJNI
#define _Included_org_wpilib_hardware_hal_CANAPIJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    initializeCAN
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_initializeCAN
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    cleanCAN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_cleanCAN
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    writeCANPacket
 * Signature: (II[BII)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_writeCANPacket
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    writeCANPacketRepeating
 * Signature: (II[BIII)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_writeCANPacketRepeating
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    writeCANRTRFrame
 * Signature: (II[BII)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_writeCANRTRFrame
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    writeCANPacketNoThrow
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_writeCANPacketNoThrow
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    writeCANPacketRepeatingNoThrow
 * Signature: (II[BIII)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_writeCANPacketRepeatingNoThrow
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    writeCANRTRFrameNoThrow
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_writeCANRTRFrameNoThrow
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    stopCANPacketRepeating
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_stopCANPacketRepeating
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    readCANPacketNew
 * Signature: (IILorg/wpilib/hardware/hal/can/CANReceiveMessage;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_readCANPacketNew
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    readCANPacketLatest
 * Signature: (IILorg/wpilib/hardware/hal/can/CANReceiveMessage;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_readCANPacketLatest
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_wpilib_hardware_hal_CANAPIJNI
 * Method:    readCANPacketTimeout
 * Signature: (IILorg/wpilib/hardware/hal/can/CANReceiveMessage;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_CANAPIJNI_readCANPacketTimeout
  (JNIEnv *, jclass, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
