/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_SimulatorJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_SimulatorJNI
#define _Included_org_wpilib_hardware_hal_simulation_SimulatorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    setRuntimeType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_setRuntimeType
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    waitForProgramStart
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_waitForProgramStart
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    setProgramStarted
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_setProgramStarted
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    getProgramStarted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_getProgramStarted
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    setProgramState
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_setProgramState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    nativeGetProgramState
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_nativeGetProgramState
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    restartTiming
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_restartTiming
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    pauseTiming
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_pauseTiming
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    resumeTiming
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_resumeTiming
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    isTimingPaused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_isTimingPaused
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    stepTiming
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_stepTiming
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    stepTimingAsync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_stepTimingAsync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_wpilib_hardware_hal_simulation_SimulatorJNI
 * Method:    resetHandles
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_SimulatorJNI_resetHandles
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
