/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_EncoderDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_EncoderDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_EncoderDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    registerInitializedCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_registerInitializedCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    cancelInitializedCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_cancelInitializedCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    getInitialized
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_getInitialized
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    setInitialized
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_setInitialized
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    registerCountCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_registerCountCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    cancelCountCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_cancelCountCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    getCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_getCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    setCount
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_setCount
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    registerRateCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_registerRateCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    cancelRateCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_cancelRateCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    registerResetCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_registerResetCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    cancelResetCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_cancelResetCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    getReset
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_getReset
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    setReset
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_setReset
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    registerDirectionCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_registerDirectionCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    cancelDirectionCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_cancelDirectionCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    getDirection
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_getDirection
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    setDirection
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_setDirection
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    registerReverseDirectionCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_registerReverseDirectionCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    cancelReverseDirectionCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_cancelReverseDirectionCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    getReverseDirection
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_getReverseDirection
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    setReverseDirection
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_setReverseDirection
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    registerDistancePerPulseCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_registerDistancePerPulseCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    cancelDistancePerPulseCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_cancelDistancePerPulseCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    getDistancePerPulse
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_getDistancePerPulse
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    setDistancePerPulse
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_setDistancePerPulse
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    setDistance
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_setDistance
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    getDistance
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_getDistance
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    setRate
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_setRate
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    getRate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_getRate
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    resetData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_resetData
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_EncoderDataJNI
 * Method:    findForChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_EncoderDataJNI_findForChannel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
