/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_PortsJNI */

#ifndef _Included_org_wpilib_hardware_hal_PortsJNI
#define _Included_org_wpilib_hardware_hal_PortsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumCanBuses
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumCanBuses
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumSmartIo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumSmartIo
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumCTREPCMModules
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumCTREPCMModules
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumCTRESolenoidChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumCTRESolenoidChannels
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumCTREPDPModules
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumCTREPDPModules
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumCTREPDPChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumCTREPDPChannels
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumREVPDHModules
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumREVPDHModules
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumREVPDHChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumREVPDHChannels
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumREVPHModules
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumREVPHModules
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_PortsJNI
 * Method:    getNumREVPHChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PortsJNI_getNumREVPHChannels
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
