/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_AddressableLEDJNI */

#ifndef _Included_org_wpilib_hardware_hal_AddressableLEDJNI
#define _Included_org_wpilib_hardware_hal_AddressableLEDJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_RGB
#define org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_RGB 0L
#undef org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_RBG
#define org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_RBG 1L
#undef org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_BGR
#define org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_BGR 2L
#undef org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_BRG
#define org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_BRG 3L
#undef org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_GBR
#define org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_GBR 4L
#undef org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_GRB
#define org_wpilib_hardware_hal_AddressableLEDJNI_COLOR_ORDER_GRB 5L
/*
 * Class:     org_wpilib_hardware_hal_AddressableLEDJNI
 * Method:    initialize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_AddressableLEDJNI_initialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_AddressableLEDJNI
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_AddressableLEDJNI_free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_AddressableLEDJNI
 * Method:    setStart
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_AddressableLEDJNI_setStart
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_AddressableLEDJNI
 * Method:    setLength
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_AddressableLEDJNI_setLength
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_AddressableLEDJNI
 * Method:    setData
 * Signature: (II[BII)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_AddressableLEDJNI_setData
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_AddressableLEDJNI
 * Method:    setDataFromBuffer
 * Signature: (IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_AddressableLEDJNI_setDataFromBuffer
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
