/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_DIODataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_DIODataJNI
#define _Included_org_wpilib_hardware_hal_simulation_DIODataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    registerInitializedCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_registerInitializedCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    cancelInitializedCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_cancelInitializedCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    getInitialized
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_getInitialized
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    setInitialized
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_setInitialized
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    registerValueCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_registerValueCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    cancelValueCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_cancelValueCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    getValue
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_getValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    setValue
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_setValue
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    registerPulseLengthCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_registerPulseLengthCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    cancelPulseLengthCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_cancelPulseLengthCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    getPulseLength
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_getPulseLength
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    setPulseLength
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_setPulseLength
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    registerIsInputCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_registerIsInputCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    cancelIsInputCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_cancelIsInputCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    getIsInput
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_getIsInput
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    setIsInput
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_setIsInput
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    registerFilterIndexCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_registerFilterIndexCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    cancelFilterIndexCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_cancelFilterIndexCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    getFilterIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_getFilterIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    setFilterIndex
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_setFilterIndex
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_DIODataJNI
 * Method:    resetData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_DIODataJNI_resetData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
