/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_PowerDistributionJNI */

#ifndef _Included_org_wpilib_hardware_hal_PowerDistributionJNI
#define _Included_org_wpilib_hardware_hal_PowerDistributionJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_wpilib_hardware_hal_PowerDistributionJNI_AUTOMATIC_TYPE
#define org_wpilib_hardware_hal_PowerDistributionJNI_AUTOMATIC_TYPE 0L
#undef org_wpilib_hardware_hal_PowerDistributionJNI_CTRE_TYPE
#define org_wpilib_hardware_hal_PowerDistributionJNI_CTRE_TYPE 1L
#undef org_wpilib_hardware_hal_PowerDistributionJNI_REV_TYPE
#define org_wpilib_hardware_hal_PowerDistributionJNI_REV_TYPE 2L
#undef org_wpilib_hardware_hal_PowerDistributionJNI_DEFAULT_MODULE
#define org_wpilib_hardware_hal_PowerDistributionJNI_DEFAULT_MODULE -1L
/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    initialize
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_initialize
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getModuleNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getModuleNumber
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    checkModule
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_checkModule
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    checkChannel
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_checkChannel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getType
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getNumChannels
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getNumChannels
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getTemperature
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getTemperature
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getVoltage
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getVoltage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getChannelCurrent
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getChannelCurrent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getAllCurrents
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getAllCurrents
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getTotalCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getTotalCurrent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getTotalPower
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getTotalPower
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getTotalEnergy
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getTotalEnergy
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    resetTotalEnergy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_resetTotalEnergy
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    clearStickyFaults
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_clearStickyFaults
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getSwitchableChannel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getSwitchableChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    setSwitchableChannel
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_setSwitchableChannel
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getVoltageNoError
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getVoltageNoError
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getChannelCurrentNoError
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getChannelCurrentNoError
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getAllCurrentsNoError
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getAllCurrentsNoError
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getTotalCurrentNoError
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getTotalCurrentNoError
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getSwitchableChannelNoError
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getSwitchableChannelNoError
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    setSwitchableChannelNoError
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_setSwitchableChannelNoError
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getFaultsNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getFaultsNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getStickyFaultsNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getStickyFaultsNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_PowerDistributionJNI
 * Method:    getVersion
 * Signature: (I)Lorg/wpilib/hardware/hal/PowerDistributionVersion;
 */
JNIEXPORT jobject JNICALL Java_org_wpilib_hardware_hal_PowerDistributionJNI_getVersion
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
