/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_DIOJNI */

#ifndef _Included_org_wpilib_hardware_hal_DIOJNI
#define _Included_org_wpilib_hardware_hal_DIOJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    initializeDIOPort
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DIOJNI_initializeDIOPort
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    checkDIOChannel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_DIOJNI_checkDIOChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    freeDIOPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_freeDIOPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    setDIOSimDevice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_setDIOSimDevice
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    setDIO
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_setDIO
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    setDIODirection
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_setDIODirection
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    getDIO
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_DIOJNI_getDIO
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    getDIODirection
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_DIOJNI_getDIODirection
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    pulse
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_pulse
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    pulseMultiple
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_pulseMultiple
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    isPulsing
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_DIOJNI_isPulsing
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    isAnyPulsing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_DIOJNI_isAnyPulsing
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    allocateDigitalPWM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DIOJNI_allocateDigitalPWM
  (JNIEnv *, jclass);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    freeDigitalPWM
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_freeDigitalPWM
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    setDigitalPWMRate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_setDigitalPWMRate
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    setDigitalPWMDutyCycle
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_setDigitalPWMDutyCycle
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    setDigitalPWMPPS
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_setDigitalPWMPPS
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_DIOJNI
 * Method:    setDigitalPWMOutputChannel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DIOJNI_setDigitalPWMOutputChannel
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
