/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_IMUDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_IMUDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_IMUDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setAngleX
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setAngleX
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setAngleY
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setAngleY
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setAngleZ
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setAngleZ
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setGyroRateX
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setGyroRateX
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setGyroRateY
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setGyroRateY
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setGyroRateZ
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setGyroRateZ
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setAccelX
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setAccelX
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setAccelY
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setAccelY
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setAccelZ
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setAccelZ
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_IMUDataJNI
 * Method:    setYaw
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_IMUDataJNI_setYaw
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
