/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_simulation_CTREPCMDataJNI */

#ifndef _Included_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
#define _Included_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    registerInitializedCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_registerInitializedCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    cancelInitializedCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_cancelInitializedCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    getInitialized
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_getInitialized
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    setInitialized
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_setInitialized
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    registerSolenoidOutputCallback
 * Signature: (IILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_registerSolenoidOutputCallback
  (JNIEnv *, jclass, jint, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    cancelSolenoidOutputCallback
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_cancelSolenoidOutputCallback
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    getSolenoidOutput
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_getSolenoidOutput
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    setSolenoidOutput
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_setSolenoidOutput
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    registerCompressorOnCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_registerCompressorOnCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    cancelCompressorOnCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_cancelCompressorOnCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    getCompressorOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_getCompressorOn
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    setCompressorOn
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_setCompressorOn
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    registerClosedLoopEnabledCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_registerClosedLoopEnabledCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    cancelClosedLoopEnabledCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_cancelClosedLoopEnabledCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    getClosedLoopEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_getClosedLoopEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    setClosedLoopEnabled
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_setClosedLoopEnabled
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    registerPressureSwitchCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_registerPressureSwitchCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    cancelPressureSwitchCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_cancelPressureSwitchCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    getPressureSwitch
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_getPressureSwitch
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    setPressureSwitch
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_setPressureSwitch
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    registerCompressorCurrentCallback
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_registerCompressorCurrentCallback
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    cancelCompressorCurrentCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_cancelCompressorCurrentCallback
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    getCompressorCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_getCompressorCurrent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    setCompressorCurrent
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_setCompressorCurrent
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    registerAllNonSolenoidCallbacks
 * Signature: (ILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_registerAllNonSolenoidCallbacks
  (JNIEnv *, jclass, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    registerAllSolenoidCallbacks
 * Signature: (IILorg/wpilib/hardware/hal/simulation/NotifyCallback;Z)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_registerAllSolenoidCallbacks
  (JNIEnv *, jclass, jint, jint, jobject, jboolean);

/*
 * Class:     org_wpilib_hardware_hal_simulation_CTREPCMDataJNI
 * Method:    resetData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_simulation_CTREPCMDataJNI_resetData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
