/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wpilib_hardware_hal_DutyCycleJNI */

#ifndef _Included_org_wpilib_hardware_hal_DutyCycleJNI
#define _Included_org_wpilib_hardware_hal_DutyCycleJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wpilib_hardware_hal_DutyCycleJNI
 * Method:    initialize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DutyCycleJNI_initialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DutyCycleJNI
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wpilib_hardware_hal_DutyCycleJNI_free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DutyCycleJNI
 * Method:    getFrequency
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_DutyCycleJNI_getFrequency
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DutyCycleJNI
 * Method:    getOutput
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_wpilib_hardware_hal_DutyCycleJNI_getOutput
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_wpilib_hardware_hal_DutyCycleJNI
 * Method:    getHighTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_wpilib_hardware_hal_DutyCycleJNI_getHighTime
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
