sonar.projectName=My First C++ Project
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.projectKey=SparkMaxAPI2
sonar.login=0d7000e97e7cf423695d63fa0f76829ae27a12e4
sonar.cfamily.build-wrapper-output="C:\Users\Will\Src\SPARK-MAX-roboRIO\build\sonarQube"

sonar.modules=java-module, cpp-module, driver-module

java-module.sonar.projectName=Java API
java-module.sonar.language=java
java-module.sonar.sources=src/main/java
java-module.sonar.binaries=target/classes
java-module.sonar.projectBaseDir=.

cpp-module.sonar.projectName=C++ Module
cpp-module.language=cpp
cpp-module.sources=src/main/native
cpp-module.projectBaseDir=.
cpp-module.cfamily.build-wrapper-output="C:\Users\Will\Src\SPARK-MAX-roboRIO\build\sonarQube"

driver-module.sonar.projectName=Driver Module
driver-module.language=cpp
driver-module.sources=src/main/driver
driver-module.projectBaseDir=.
driver-module.cfamily.build-wrapper-output="C:\Users\Will\Src\SPARK-MAX-roboRIO\build\sonarQube"
