/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Generated by cantools 39.4.5 with automatic customizations by REV from public
 * FIRST MotorController spec version 0.0.1-dev.0
 */

#include "first/CANA301Frames.h"

#include <string.h>

static inline uint8_t pack_left_shift_u8(uint8_t value, uint8_t shift,
                                         uint8_t mask) {
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(uint16_t value, uint8_t shift,
                                          uint8_t mask) {
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(uint32_t value, uint8_t shift,
                                          uint8_t mask) {
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(uint16_t value, uint8_t shift,
                                           uint8_t mask) {
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(uint32_t value, uint8_t shift,
                                           uint8_t mask) {
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(uint8_t value, uint8_t shift,
                                             uint8_t mask) {
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(uint8_t value, uint8_t shift,
                                             uint8_t mask) {
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(uint8_t value, uint8_t shift,
                                            uint8_t mask) {
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(uint8_t value, uint8_t shift,
                                              uint8_t mask) {
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(uint8_t value, uint8_t shift,
                                              uint8_t mask) {
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int a301_velocity_setpoint_pack(uint8_t *dst_p,
                                const a301_velocity_setpoint_t *src_p,
                                size_t size) {
    uint32_t setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&setpoint, &src_p->setpoint, sizeof(setpoint));
    dst_p[0] |= pack_left_shift_u32(setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(setpoint, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(setpoint, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(setpoint, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->reserved, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->reserved, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->reserved, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->reserved, 24u, 0xffu);

    return (8);
}

int a301_velocity_setpoint_unpack(a301_velocity_setpoint_t *dst_p,
                                  const uint8_t *src_p, size_t size) {
    uint32_t setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    setpoint = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->setpoint, &setpoint, sizeof(dst_p->setpoint));
    dst_p->reserved = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int a301_velocity_setpoint_init(a301_velocity_setpoint_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_velocity_setpoint_t));

    return 0;
}

float a301_velocity_setpoint_setpoint_encode(double value) {
    return (float)(value);
}

double a301_velocity_setpoint_setpoint_decode(float value) {
    return ((double)value);
}

bool a301_velocity_setpoint_setpoint_is_in_range(float value) {
    (void)value;

    return (true);
}

uint32_t a301_velocity_setpoint_reserved_encode(double value) {
    return (uint32_t)(value);
}

double a301_velocity_setpoint_reserved_decode(uint32_t value) {
    return ((double)value);
}

bool a301_velocity_setpoint_reserved_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int a301_duty_cycle_setpoint_pack(uint8_t *dst_p,
                                  const a301_duty_cycle_setpoint_t *src_p,
                                  size_t size) {
    uint32_t setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&setpoint, &src_p->setpoint, sizeof(setpoint));
    dst_p[0] |= pack_left_shift_u32(setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(setpoint, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(setpoint, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(setpoint, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->reserved, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->reserved, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->reserved, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->reserved, 24u, 0xffu);

    return (8);
}

int a301_duty_cycle_setpoint_unpack(a301_duty_cycle_setpoint_t *dst_p,
                                    const uint8_t *src_p, size_t size) {
    uint32_t setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    setpoint = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->setpoint, &setpoint, sizeof(dst_p->setpoint));
    dst_p->reserved = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int a301_duty_cycle_setpoint_init(a301_duty_cycle_setpoint_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_duty_cycle_setpoint_t));

    return 0;
}

float a301_duty_cycle_setpoint_setpoint_encode(double value) {
    return (float)(value);
}

double a301_duty_cycle_setpoint_setpoint_decode(float value) {
    return ((double)value);
}

bool a301_duty_cycle_setpoint_setpoint_is_in_range(float value) {
    (void)value;

    return (true);
}

uint32_t a301_duty_cycle_setpoint_reserved_encode(double value) {
    return (uint32_t)(value);
}

double a301_duty_cycle_setpoint_reserved_decode(uint32_t value) {
    return ((double)value);
}

bool a301_duty_cycle_setpoint_reserved_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int a301_relative_position_setpoint_pack(
    uint8_t *dst_p, const a301_relative_position_setpoint_t *src_p,
    size_t size) {
    uint32_t setpoint;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&setpoint, &src_p->setpoint, sizeof(setpoint));
    dst_p[0] |= pack_left_shift_u32(setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(setpoint, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(setpoint, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(setpoint, 24u, 0xffu);
    memcpy(&velocity, &src_p->velocity, sizeof(velocity));
    dst_p[4] |= pack_left_shift_u32(velocity, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(velocity, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(velocity, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(velocity, 24u, 0xffu);

    return (8);
}

int a301_relative_position_setpoint_unpack(
    a301_relative_position_setpoint_t *dst_p, const uint8_t *src_p,
    size_t size) {
    uint32_t setpoint;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    setpoint = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->setpoint, &setpoint, sizeof(dst_p->setpoint));
    velocity = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->velocity, &velocity, sizeof(dst_p->velocity));

    return (0);
}

int a301_relative_position_setpoint_init(
    a301_relative_position_setpoint_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_relative_position_setpoint_t));

    return 0;
}

float a301_relative_position_setpoint_setpoint_encode(double value) {
    return (float)(value);
}

double a301_relative_position_setpoint_setpoint_decode(float value) {
    return ((double)value);
}

bool a301_relative_position_setpoint_setpoint_is_in_range(float value) {
    (void)value;

    return (true);
}

float a301_relative_position_setpoint_velocity_encode(double value) {
    return (float)(value);
}

double a301_relative_position_setpoint_velocity_decode(float value) {
    return ((double)value);
}

bool a301_relative_position_setpoint_velocity_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_current_setpoint_pack(uint8_t *dst_p,
                               const a301_current_setpoint_t *src_p,
                               size_t size) {
    uint32_t setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&setpoint, &src_p->setpoint, sizeof(setpoint));
    dst_p[0] |= pack_left_shift_u32(setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(setpoint, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(setpoint, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(setpoint, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->reserved, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->reserved, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->reserved, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->reserved, 24u, 0xffu);

    return (8);
}

int a301_current_setpoint_unpack(a301_current_setpoint_t *dst_p,
                                 const uint8_t *src_p, size_t size) {
    uint32_t setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    setpoint = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->setpoint, &setpoint, sizeof(dst_p->setpoint));
    dst_p->reserved = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int a301_current_setpoint_init(a301_current_setpoint_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_current_setpoint_t));

    return 0;
}

float a301_current_setpoint_setpoint_encode(double value) {
    return (float)(value);
}

double a301_current_setpoint_setpoint_decode(float value) {
    return ((double)value);
}

bool a301_current_setpoint_setpoint_is_in_range(float value) {
    (void)value;

    return (true);
}

uint32_t a301_current_setpoint_reserved_encode(double value) {
    return (uint32_t)(value);
}

double a301_current_setpoint_reserved_decode(uint32_t value) {
    return ((double)value);
}

bool a301_current_setpoint_reserved_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int a301_absolute_position_setpoint_pack(
    uint8_t *dst_p, const a301_absolute_position_setpoint_t *src_p,
    size_t size) {
    uint32_t setpoint;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&setpoint, &src_p->setpoint, sizeof(setpoint));
    dst_p[0] |= pack_left_shift_u32(setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(setpoint, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(setpoint, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(setpoint, 24u, 0xffu);
    memcpy(&velocity, &src_p->velocity, sizeof(velocity));
    dst_p[4] |= pack_left_shift_u32(velocity, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(velocity, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(velocity, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(velocity, 24u, 0xffu);

    return (8);
}

int a301_absolute_position_setpoint_unpack(
    a301_absolute_position_setpoint_t *dst_p, const uint8_t *src_p,
    size_t size) {
    uint32_t setpoint;
    uint32_t velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    setpoint = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    setpoint |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->setpoint, &setpoint, sizeof(dst_p->setpoint));
    velocity = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    velocity |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->velocity, &velocity, sizeof(dst_p->velocity));

    return (0);
}

int a301_absolute_position_setpoint_init(
    a301_absolute_position_setpoint_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_absolute_position_setpoint_t));

    return 0;
}

float a301_absolute_position_setpoint_setpoint_encode(double value) {
    return (float)(value);
}

double a301_absolute_position_setpoint_setpoint_decode(float value) {
    return ((double)value);
}

bool a301_absolute_position_setpoint_setpoint_is_in_range(float value) {
    (void)value;

    return (true);
}

float a301_absolute_position_setpoint_velocity_encode(double value) {
    return (float)(value);
}

double a301_absolute_position_setpoint_velocity_decode(float value) {
    return ((double)value);
}

bool a301_absolute_position_setpoint_velocity_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_clear_faults_pack(uint8_t *dst_p, const a301_clear_faults_t *src_p,
                           size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_clear_faults_unpack(a301_clear_faults_t *dst_p, const uint8_t *src_p,
                             size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_identify_pack(uint8_t *dst_p, const a301_identify_t *src_p,
                       size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_identify_unpack(a301_identify_t *dst_p, const uint8_t *src_p,
                         size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_firmware_version_pack(uint8_t *dst_p,
                                   const a301_get_firmware_version_t *src_p,
                                   size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->major, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->minor, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->patch, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->patch, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->prerelease, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->hw_rev, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->reserved, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->reserved, 8u, 0xffu);

    return (8);
}

int a301_get_firmware_version_unpack(a301_get_firmware_version_t *dst_p,
                                     const uint8_t *src_p, size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->major = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->minor = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->patch = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->patch |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->prerelease = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->hw_rev = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->reserved = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int a301_get_firmware_version_init(a301_get_firmware_version_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_get_firmware_version_t));

    return 0;
}

uint8_t a301_get_firmware_version_major_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_firmware_version_major_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_firmware_version_major_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t a301_get_firmware_version_minor_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_firmware_version_minor_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_firmware_version_minor_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint16_t a301_get_firmware_version_patch_encode(double value) {
    return (uint16_t)(value);
}

double a301_get_firmware_version_patch_decode(uint16_t value) {
    return ((double)value);
}

bool a301_get_firmware_version_patch_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint8_t a301_get_firmware_version_prerelease_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_firmware_version_prerelease_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_firmware_version_prerelease_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t a301_get_firmware_version_hw_rev_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_firmware_version_hw_rev_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_firmware_version_hw_rev_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint16_t a301_get_firmware_version_reserved_encode(double value) {
    return (uint16_t)(value);
}

double a301_get_firmware_version_reserved_decode(uint16_t value) {
    return ((double)value);
}

bool a301_get_firmware_version_reserved_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

int a301_set_relative_encoder_position_pack(
    uint8_t *dst_p, const a301_set_relative_encoder_position_t *src_p,
    size_t size) {
    uint32_t position;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    memcpy(&position, &src_p->position, sizeof(position));
    dst_p[0] |= pack_left_shift_u32(position, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(position, 24u, 0xffu);

    return (4);
}

int a301_set_relative_encoder_position_unpack(
    a301_set_relative_encoder_position_t *dst_p, const uint8_t *src_p,
    size_t size) {
    uint32_t position;

    if (size < 4u) {
        return (-EINVAL);
    }

    position = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->position, &position, sizeof(dst_p->position));

    return (0);
}

int a301_set_relative_encoder_position_init(
    a301_set_relative_encoder_position_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_relative_encoder_position_t));

    return 0;
}

float a301_set_relative_encoder_position_position_encode(double value) {
    return (float)(value);
}

double a301_set_relative_encoder_position_position_decode(float value) {
    return ((double)value);
}

bool a301_set_relative_encoder_position_position_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_set_relative_position_response_pack(
    uint8_t *dst_p, const a301_set_relative_position_response_t *src_p,
    size_t size) {
    uint32_t position;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    memcpy(&position, &src_p->position, sizeof(position));
    dst_p[0] |= pack_left_shift_u32(position, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(position, 24u, 0xffu);

    return (4);
}

int a301_set_relative_position_response_unpack(
    a301_set_relative_position_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    uint32_t position;

    if (size < 4u) {
        return (-EINVAL);
    }

    position = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->position, &position, sizeof(dst_p->position));

    return (0);
}

int a301_set_relative_position_response_init(
    a301_set_relative_position_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_relative_position_response_t));

    return 0;
}

float a301_set_relative_position_response_position_encode(double value) {
    return (float)(value);
}

double a301_set_relative_position_response_position_decode(float value) {
    return ((double)value);
}

bool a301_set_relative_position_response_position_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_set_absolute_encoder_position_pack(
    uint8_t *dst_p, const a301_set_absolute_encoder_position_t *src_p,
    size_t size) {
    uint32_t position;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    memcpy(&position, &src_p->position, sizeof(position));
    dst_p[0] |= pack_left_shift_u32(position, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(position, 24u, 0xffu);

    return (4);
}

int a301_set_absolute_encoder_position_unpack(
    a301_set_absolute_encoder_position_t *dst_p, const uint8_t *src_p,
    size_t size) {
    uint32_t position;

    if (size < 4u) {
        return (-EINVAL);
    }

    position = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->position, &position, sizeof(dst_p->position));

    return (0);
}

int a301_set_absolute_encoder_position_init(
    a301_set_absolute_encoder_position_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_absolute_encoder_position_t));

    return 0;
}

float a301_set_absolute_encoder_position_position_encode(double value) {
    return (float)(value);
}

double a301_set_absolute_encoder_position_position_decode(float value) {
    return ((double)value);
}

bool a301_set_absolute_encoder_position_position_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_set_absolute_position_response_pack(
    uint8_t *dst_p, const a301_set_absolute_position_response_t *src_p,
    size_t size) {
    uint32_t position;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    memcpy(&position, &src_p->position, sizeof(position));
    dst_p[0] |= pack_left_shift_u32(position, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(position, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(position, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(position, 24u, 0xffu);

    return (4);
}

int a301_set_absolute_position_response_unpack(
    a301_set_absolute_position_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    uint32_t position;

    if (size < 4u) {
        return (-EINVAL);
    }

    position = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    position |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    position |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    position |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->position, &position, sizeof(dst_p->position));

    return (0);
}

int a301_set_absolute_position_response_init(
    a301_set_absolute_position_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_absolute_position_response_t));

    return 0;
}

float a301_set_absolute_position_response_position_encode(double value) {
    return (float)(value);
}

double a301_set_absolute_position_response_position_decode(float value) {
    return ((double)value);
}

bool a301_set_absolute_position_response_position_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_set_continuous_input_pack(uint8_t *dst_p,
                                   const a301_set_continuous_input_t *src_p,
                                   size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->enabled, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->reserved, 1u, 0xfeu);

    return (1);
}

int a301_set_continuous_input_unpack(a301_set_continuous_input_t *dst_p,
                                     const uint8_t *src_p, size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->enabled = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->reserved = unpack_right_shift_u8(src_p[0], 1u, 0xfeu);

    return (0);
}

int a301_set_continuous_input_init(a301_set_continuous_input_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_continuous_input_t));

    return 0;
}

uint8_t a301_set_continuous_input_enabled_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_continuous_input_enabled_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_continuous_input_enabled_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_set_continuous_input_reserved_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_continuous_input_reserved_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_continuous_input_reserved_is_in_range(uint8_t value) {
    return (value <= 127u);
}

int a301_set_continuous_input_response_pack(
    uint8_t *dst_p, const a301_set_continuous_input_response_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->enabled, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->reserved, 1u, 0xfeu);

    return (1);
}

int a301_set_continuous_input_response_unpack(
    a301_set_continuous_input_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->enabled = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->reserved = unpack_right_shift_u8(src_p[0], 1u, 0xfeu);

    return (0);
}

int a301_set_continuous_input_response_init(
    a301_set_continuous_input_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_continuous_input_response_t));

    return 0;
}

uint8_t a301_set_continuous_input_response_enabled_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_continuous_input_response_enabled_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_continuous_input_response_enabled_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_set_continuous_input_response_reserved_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_continuous_input_response_reserved_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_continuous_input_response_reserved_is_in_range(uint8_t value) {
    return (value <= 127u);
}

int a301_set_abs_range_offset_pack(uint8_t *dst_p,
                                   const a301_set_abs_range_offset_t *src_p,
                                   size_t size) {
    uint32_t offset;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    memcpy(&offset, &src_p->offset, sizeof(offset));
    dst_p[0] |= pack_left_shift_u32(offset, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(offset, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(offset, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(offset, 24u, 0xffu);

    return (4);
}

int a301_set_abs_range_offset_unpack(a301_set_abs_range_offset_t *dst_p,
                                     const uint8_t *src_p, size_t size) {
    uint32_t offset;

    if (size < 4u) {
        return (-EINVAL);
    }

    offset = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->offset, &offset, sizeof(dst_p->offset));

    return (0);
}

int a301_set_abs_range_offset_init(a301_set_abs_range_offset_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_abs_range_offset_t));

    return 0;
}

float a301_set_abs_range_offset_offset_encode(double value) {
    return (float)(value);
}

double a301_set_abs_range_offset_offset_decode(float value) {
    return ((double)value);
}

bool a301_set_abs_range_offset_offset_is_in_range(float value) {
    return ((value >= -0.5f) && (value <= 0.5f));
}

int a301_set_abs_range_offset_response_pack(
    uint8_t *dst_p, const a301_set_abs_range_offset_response_t *src_p,
    size_t size) {
    uint32_t offset;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    memcpy(&offset, &src_p->offset, sizeof(offset));
    dst_p[0] |= pack_left_shift_u32(offset, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(offset, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(offset, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(offset, 24u, 0xffu);

    return (4);
}

int a301_set_abs_range_offset_response_unpack(
    a301_set_abs_range_offset_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    uint32_t offset;

    if (size < 4u) {
        return (-EINVAL);
    }

    offset = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->offset, &offset, sizeof(dst_p->offset));

    return (0);
}

int a301_set_abs_range_offset_response_init(
    a301_set_abs_range_offset_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_abs_range_offset_response_t));

    return 0;
}

float a301_set_abs_range_offset_response_offset_encode(double value) {
    return (float)(value);
}

double a301_set_abs_range_offset_response_offset_decode(float value) {
    return ((double)value);
}

bool a301_set_abs_range_offset_response_offset_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_set_can_id_pack(uint8_t *dst_p, const a301_set_can_id_t *src_p,
                         size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);

    return (1);
}

int a301_set_can_id_unpack(a301_set_can_id_t *dst_p, const uint8_t *src_p,
                           size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int a301_set_can_id_init(a301_set_can_id_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_can_id_t));

    return 0;
}

uint8_t a301_set_can_id_id_encode(double value) { return (uint8_t)(value); }

double a301_set_can_id_id_decode(uint8_t value) { return ((double)value); }

bool a301_set_can_id_id_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int a301_set_can_id_response_pack(uint8_t *dst_p,
                                  const a301_set_can_id_response_t *src_p,
                                  size_t size) {
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->writeresult, 0u, 0xffu);

    return (2);
}

int a301_set_can_id_response_unpack(a301_set_can_id_response_t *dst_p,
                                    const uint8_t *src_p, size_t size) {
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->writeresult = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int a301_set_can_id_response_init(a301_set_can_id_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_can_id_response_t));

    return 0;
}

uint8_t a301_set_can_id_response_id_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_can_id_response_id_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_can_id_response_id_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t a301_set_can_id_response_writeresult_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_can_id_response_writeresult_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_can_id_response_writeresult_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int a301_set_idle_mode_pack(uint8_t *dst_p, const a301_set_idle_mode_t *src_p,
                            size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->idle_mode, 0u, 0xffu);

    return (1);
}

int a301_set_idle_mode_unpack(a301_set_idle_mode_t *dst_p, const uint8_t *src_p,
                              size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->idle_mode = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int a301_set_idle_mode_init(a301_set_idle_mode_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_idle_mode_t));

    return 0;
}

uint8_t a301_set_idle_mode_idle_mode_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_idle_mode_idle_mode_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_idle_mode_idle_mode_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int a301_set_idle_mode_response_pack(uint8_t *dst_p,
                                     const a301_set_idle_mode_response_t *src_p,
                                     size_t size) {
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->idle_mode, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->writeresult, 0u, 0xffu);

    return (2);
}

int a301_set_idle_mode_response_unpack(a301_set_idle_mode_response_t *dst_p,
                                       const uint8_t *src_p, size_t size) {
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->idle_mode = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->writeresult = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int a301_set_idle_mode_response_init(a301_set_idle_mode_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_idle_mode_response_t));

    return 0;
}

uint8_t a301_set_idle_mode_response_idle_mode_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_idle_mode_response_idle_mode_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_idle_mode_response_idle_mode_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t a301_set_idle_mode_response_writeresult_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_idle_mode_response_writeresult_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_idle_mode_response_writeresult_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int a301_set_status_period_pack(uint8_t *dst_p,
                                const a301_set_status_period_t *src_p,
                                size_t size) {
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->periodic_frame, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u32(src_p->period, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->period, 8u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->period, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->period, 24u, 0xffu);

    return (5);
}

int a301_set_status_period_unpack(a301_set_status_period_t *dst_p,
                                  const uint8_t *src_p, size_t size) {
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->periodic_frame = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->period = unpack_right_shift_u32(src_p[1], 0u, 0xffu);
    dst_p->period |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->period |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->period |= unpack_left_shift_u32(src_p[4], 24u, 0xffu);

    return (0);
}

int a301_set_status_period_init(a301_set_status_period_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_status_period_t));

    return 0;
}

uint8_t a301_set_status_period_periodic_frame_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_status_period_periodic_frame_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_status_period_periodic_frame_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint32_t a301_set_status_period_period_encode(double value) {
    return (uint32_t)(value);
}

double a301_set_status_period_period_decode(uint32_t value) {
    return ((double)value);
}

bool a301_set_status_period_period_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int a301_set_status_period_response_pack(
    uint8_t *dst_p, const a301_set_status_period_response_t *src_p,
    size_t size) {
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->result_code, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->specified_periodic_frame, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->status_period, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->status_period, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->status_period, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->status_period, 24u, 0xffu);

    return (6);
}

int a301_set_status_period_response_unpack(
    a301_set_status_period_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->result_code = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->specified_periodic_frame =
        unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->status_period = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->status_period |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->status_period |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->status_period |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);

    return (0);
}

int a301_set_status_period_response_init(
    a301_set_status_period_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_set_status_period_response_t));

    return 0;
}

uint8_t a301_set_status_period_response_result_code_encode(double value) {
    return (uint8_t)(value);
}

double a301_set_status_period_response_result_code_decode(uint8_t value) {
    return ((double)value);
}

bool a301_set_status_period_response_result_code_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t a301_set_status_period_response_specified_periodic_frame_encode(
    double value) {
    return (uint8_t)(value);
}

double a301_set_status_period_response_specified_periodic_frame_decode(
    uint8_t value) {
    return ((double)value);
}

bool a301_set_status_period_response_specified_periodic_frame_is_in_range(
    uint8_t value) {
    (void)value;

    return (true);
}

uint32_t a301_set_status_period_response_status_period_encode(double value) {
    return (uint32_t)(value);
}

double a301_set_status_period_response_status_period_decode(uint32_t value) {
    return ((double)value);
}

bool a301_set_status_period_response_status_period_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int a301_get_can_id_pack(uint8_t *dst_p, const a301_get_can_id_t *src_p,
                         size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_can_id_unpack(a301_get_can_id_t *dst_p, const uint8_t *src_p,
                           size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_can_id_response_pack(uint8_t *dst_p,
                                  const a301_get_can_id_response_t *src_p,
                                  size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);

    return (1);
}

int a301_get_can_id_response_unpack(a301_get_can_id_response_t *dst_p,
                                    const uint8_t *src_p, size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int a301_get_can_id_response_init(a301_get_can_id_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_get_can_id_response_t));

    return 0;
}

uint8_t a301_get_can_id_response_id_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_can_id_response_id_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_can_id_response_id_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int a301_get_idle_mode_pack(uint8_t *dst_p, const a301_get_idle_mode_t *src_p,
                            size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_idle_mode_unpack(a301_get_idle_mode_t *dst_p, const uint8_t *src_p,
                              size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_idle_mode_response_pack(uint8_t *dst_p,
                                     const a301_get_idle_mode_response_t *src_p,
                                     size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->idle_mode, 0u, 0xffu);

    return (1);
}

int a301_get_idle_mode_response_unpack(a301_get_idle_mode_response_t *dst_p,
                                       const uint8_t *src_p, size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->idle_mode = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int a301_get_idle_mode_response_init(a301_get_idle_mode_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_get_idle_mode_response_t));

    return 0;
}

uint8_t a301_get_idle_mode_response_idle_mode_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_idle_mode_response_idle_mode_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_idle_mode_response_idle_mode_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int a301_get_continuous_input_pack(uint8_t *dst_p,
                                   const a301_get_continuous_input_t *src_p,
                                   size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_continuous_input_unpack(a301_get_continuous_input_t *dst_p,
                                     const uint8_t *src_p, size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_continuous_input_response_pack(
    uint8_t *dst_p, const a301_get_continuous_input_response_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->enabled, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->reserved, 1u, 0xfeu);

    return (1);
}

int a301_get_continuous_input_response_unpack(
    a301_get_continuous_input_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->enabled = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->reserved = unpack_right_shift_u8(src_p[0], 1u, 0xfeu);

    return (0);
}

int a301_get_continuous_input_response_init(
    a301_get_continuous_input_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_get_continuous_input_response_t));

    return 0;
}

uint8_t a301_get_continuous_input_response_enabled_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_continuous_input_response_enabled_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_continuous_input_response_enabled_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_get_continuous_input_response_reserved_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_continuous_input_response_reserved_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_continuous_input_response_reserved_is_in_range(uint8_t value) {
    return (value <= 127u);
}

int a301_get_abs_range_offset_pack(uint8_t *dst_p,
                                   const a301_get_abs_range_offset_t *src_p,
                                   size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_abs_range_offset_unpack(a301_get_abs_range_offset_t *dst_p,
                                     const uint8_t *src_p, size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_abs_range_offset_response_pack(
    uint8_t *dst_p, const a301_get_abs_range_offset_response_t *src_p,
    size_t size) {
    uint32_t offset;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    memcpy(&offset, &src_p->offset, sizeof(offset));
    dst_p[0] |= pack_left_shift_u32(offset, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(offset, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(offset, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(offset, 24u, 0xffu);

    return (4);
}

int a301_get_abs_range_offset_response_unpack(
    a301_get_abs_range_offset_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    uint32_t offset;

    if (size < 4u) {
        return (-EINVAL);
    }

    offset = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    offset |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->offset, &offset, sizeof(dst_p->offset));

    return (0);
}

int a301_get_abs_range_offset_response_init(
    a301_get_abs_range_offset_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_get_abs_range_offset_response_t));

    return 0;
}

float a301_get_abs_range_offset_response_offset_encode(double value) {
    return (float)(value);
}

double a301_get_abs_range_offset_response_offset_decode(float value) {
    return ((double)value);
}

bool a301_get_abs_range_offset_response_offset_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_get_hardware_version_pack(uint8_t *dst_p,
                                   const a301_get_hardware_version_t *src_p,
                                   size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_hardware_version_unpack(a301_get_hardware_version_t *dst_p,
                                     const uint8_t *src_p, size_t size) {
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int a301_get_hardware_version_response_pack(
    uint8_t *dst_p, const a301_get_hardware_version_response_t *src_p,
    size_t size) {
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->major_version, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->minor_version, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->minor_version, 8u, 0xffu);

    return (3);
}

int a301_get_hardware_version_response_unpack(
    a301_get_hardware_version_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->major_version = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->minor_version = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->minor_version |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);

    return (0);
}

int a301_get_hardware_version_response_init(
    a301_get_hardware_version_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_get_hardware_version_response_t));

    return 0;
}

uint8_t a301_get_hardware_version_response_major_version_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_hardware_version_response_major_version_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_hardware_version_response_major_version_is_in_range(
    uint8_t value) {
    (void)value;

    return (true);
}

uint16_t a301_get_hardware_version_response_minor_version_encode(double value) {
    return (uint16_t)(value);
}

double a301_get_hardware_version_response_minor_version_decode(uint16_t value) {
    return ((double)value);
}

bool a301_get_hardware_version_response_minor_version_is_in_range(
    uint16_t value) {
    (void)value;

    return (true);
}

int a301_get_status_period_pack(uint8_t *dst_p,
                                const a301_get_status_period_t *src_p,
                                size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->periodic_frame, 0u, 0xffu);

    return (1);
}

int a301_get_status_period_unpack(a301_get_status_period_t *dst_p,
                                  const uint8_t *src_p, size_t size) {
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->periodic_frame = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int a301_get_status_period_init(a301_get_status_period_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_get_status_period_t));

    return 0;
}

uint8_t a301_get_status_period_periodic_frame_encode(double value) {
    return (uint8_t)(value);
}

double a301_get_status_period_periodic_frame_decode(uint8_t value) {
    return ((double)value);
}

bool a301_get_status_period_periodic_frame_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

int a301_get_status_period_response_pack(
    uint8_t *dst_p, const a301_get_status_period_response_t *src_p,
    size_t size) {
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->specified_periodic_frame, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u32(src_p->status_period, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->status_period, 8u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->status_period, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->status_period, 24u, 0xffu);

    return (5);
}

int a301_get_status_period_response_unpack(
    a301_get_status_period_response_t *dst_p, const uint8_t *src_p,
    size_t size) {
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->specified_periodic_frame =
        unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->status_period = unpack_right_shift_u32(src_p[1], 0u, 0xffu);
    dst_p->status_period |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->status_period |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->status_period |= unpack_left_shift_u32(src_p[4], 24u, 0xffu);

    return (0);
}

int a301_get_status_period_response_init(
    a301_get_status_period_response_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_get_status_period_response_t));

    return 0;
}

uint8_t a301_get_status_period_response_specified_periodic_frame_encode(
    double value) {
    return (uint8_t)(value);
}

double a301_get_status_period_response_specified_periodic_frame_decode(
    uint8_t value) {
    return ((double)value);
}

bool a301_get_status_period_response_specified_periodic_frame_is_in_range(
    uint8_t value) {
    (void)value;

    return (true);
}

uint32_t a301_get_status_period_response_status_period_encode(double value) {
    return (uint32_t)(value);
}

double a301_get_status_period_response_status_period_decode(uint32_t value) {
    return ((double)value);
}

bool a301_get_status_period_response_status_period_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int a301_bootloader_0_pack(uint8_t *dst_p, const a301_bootloader_0_t *src_p,
                           size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bl_major, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bl_minor, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->product_id, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->product_id, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->rsvd, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->rsvd, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->rsvd, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->rsvd, 24u, 0xffu);

    return (8);
}

int a301_bootloader_0_unpack(a301_bootloader_0_t *dst_p, const uint8_t *src_p,
                             size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bl_major = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bl_minor = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->product_id = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->product_id |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rsvd = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->rsvd |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->rsvd |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->rsvd |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int a301_bootloader_0_init(a301_bootloader_0_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_bootloader_0_t));

    return 0;
}

uint8_t a301_bootloader_0_bl_major_encode(double value) {
    return (uint8_t)(value);
}

double a301_bootloader_0_bl_major_decode(uint8_t value) {
    return ((double)value);
}

bool a301_bootloader_0_bl_major_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t a301_bootloader_0_bl_minor_encode(double value) {
    return (uint8_t)(value);
}

double a301_bootloader_0_bl_minor_decode(uint8_t value) {
    return ((double)value);
}

bool a301_bootloader_0_bl_minor_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint16_t a301_bootloader_0_product_id_encode(double value) {
    return (uint16_t)(value);
}

double a301_bootloader_0_product_id_decode(uint16_t value) {
    return ((double)value);
}

bool a301_bootloader_0_product_id_is_in_range(uint16_t value) {
    (void)value;

    return (true);
}

uint32_t a301_bootloader_0_rsvd_encode(double value) {
    return (uint32_t)(value);
}

double a301_bootloader_0_rsvd_decode(uint32_t value) { return ((double)value); }

bool a301_bootloader_0_rsvd_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

int a301_status_0_pack(uint8_t *dst_p, const a301_status_0_t *src_p,
                       size_t size) {
    uint16_t applied_output;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    applied_output = (uint16_t)src_p->applied_output;
    dst_p[0] |= pack_left_shift_u16(applied_output, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(applied_output, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->voltage, 8u, 0x0fu);
    dst_p[3] |= pack_left_shift_u16(src_p->current, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->current, 4u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->motor_temperature, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->primary_heartbeat_lock, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->gearbox_rpm, 1u, 0x1eu);
    dst_p[6] |= pack_left_shift_u16(src_p->reserved, 5u, 0xe0u);
    dst_p[7] |= pack_right_shift_u16(src_p->reserved, 3u, 0xffu);

    return (8);
}

int a301_status_0_unpack(a301_status_0_t *dst_p, const uint8_t *src_p,
                         size_t size) {
    uint16_t applied_output;

    if (size < 8u) {
        return (-EINVAL);
    }

    applied_output = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    applied_output |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->applied_output = (int16_t)applied_output;
    dst_p->voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[3], 8u, 0x0fu);
    dst_p->current = unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->current |= unpack_left_shift_u16(src_p[4], 4u, 0xffu);
    dst_p->motor_temperature = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->primary_heartbeat_lock = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->gearbox_rpm = unpack_right_shift_u8(src_p[6], 1u, 0x1eu);
    dst_p->reserved = unpack_right_shift_u16(src_p[6], 5u, 0xe0u);
    dst_p->reserved |= unpack_left_shift_u16(src_p[7], 3u, 0xffu);

    return (0);
}

int a301_status_0_init(a301_status_0_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_status_0_t));

    return 0;
}

int16_t a301_status_0_applied_output_encode(double value) {
    return (int16_t)(value / 3.082369457075716e-05);
}

double a301_status_0_applied_output_decode(int16_t value) {
    return ((double)value * 3.082369457075716e-05);
}

bool a301_status_0_applied_output_is_in_range(int16_t value) {
    return ((value >= -32443) && (value <= 32443));
}

uint16_t a301_status_0_voltage_encode(double value) {
    return (uint16_t)(value / 0.0073260073260073);
}

double a301_status_0_voltage_decode(uint16_t value) {
    return ((double)value * 0.0073260073260073);
}

bool a301_status_0_voltage_is_in_range(uint16_t value) {
    return (value <= 4095u);
}

uint16_t a301_status_0_current_encode(double value) {
    return (uint16_t)(value / 0.0366300366300366);
}

double a301_status_0_current_decode(uint16_t value) {
    return ((double)value * 0.0366300366300366);
}

bool a301_status_0_current_is_in_range(uint16_t value) {
    return (value <= 4095u);
}

uint8_t a301_status_0_motor_temperature_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_0_motor_temperature_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_0_motor_temperature_is_in_range(uint8_t value) {
    (void)value;

    return (true);
}

uint8_t a301_status_0_primary_heartbeat_lock_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_0_primary_heartbeat_lock_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_0_primary_heartbeat_lock_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_0_gearbox_rpm_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_0_gearbox_rpm_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_0_gearbox_rpm_is_in_range(uint8_t value) {
    return (value <= 15u);
}

uint16_t a301_status_0_reserved_encode(double value) {
    return (uint16_t)(value);
}

double a301_status_0_reserved_decode(uint16_t value) { return ((double)value); }

bool a301_status_0_reserved_is_in_range(uint16_t value) {
    return (value <= 2047u);
}

int a301_status_1_pack(uint8_t *dst_p, const a301_status_1_t *src_p,
                       size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->other_fault, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->motor_type_fault, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->sensor_fault, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->can_fault, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->temperature_fault, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->drv_fault, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->esc_eeprom_fault, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->firmware_fault, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->motor_startup_fault, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->reserved_actives, 1u, 0x3eu);
    dst_p[1] |= pack_left_shift_u8(src_p->overvoltage_warning, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->motor_loop_speed_warning, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->brownout_warning, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->overcurrent_warning, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->esc_eeprom_warning, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->ext_eeprom_warning, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->sensor_warning, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->stall_warning, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->has_reset_warning, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->other_warning, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->other_sticky_fault, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->motor_type_sticky_fault, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->sensor_sticky_fault, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->can_sticky_fault, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->temperature_sticky_fault, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->drv_sticky_fault, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->esc_eeprom_sticky_fault, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->firmware_sticky_fault, 7u, 0x80u);
    dst_p[4] |=
        pack_left_shift_u8(src_p->motor_startup_sticky_fault, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->reserved_stickies, 1u, 0x3eu);
    dst_p[4] |=
        pack_left_shift_u8(src_p->overvoltage_sticky_warning, 6u, 0x40u);
    dst_p[4] |=
        pack_left_shift_u8(src_p->motor_loop_speed_sticky_warning, 7u, 0x80u);
    dst_p[5] |= pack_left_shift_u8(src_p->brownout_sticky_warning, 0u, 0x01u);
    dst_p[5] |=
        pack_left_shift_u8(src_p->overcurrent_sticky_warning, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->esc_eeprom_sticky_warning, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->ext_eeprom_sticky_warning, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->sensor_sticky_warning, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->stall_sticky_warning, 5u, 0x20u);
    dst_p[5] |= pack_left_shift_u8(src_p->has_reset_sticky_warning, 6u, 0x40u);
    dst_p[5] |= pack_left_shift_u8(src_p->other_sticky_warning, 7u, 0x80u);
    dst_p[6] |= pack_left_shift_u8(src_p->is_follower, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u16(src_p->reserved, 1u, 0xfeu);
    dst_p[7] |= pack_right_shift_u16(src_p->reserved, 7u, 0xffu);

    return (8);
}

int a301_status_1_unpack(a301_status_1_t *dst_p, const uint8_t *src_p,
                         size_t size) {
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->other_fault = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->motor_type_fault = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->sensor_fault = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->can_fault = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->temperature_fault = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->drv_fault = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->esc_eeprom_fault = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->firmware_fault = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->motor_startup_fault = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->reserved_actives = unpack_right_shift_u8(src_p[1], 1u, 0x3eu);
    dst_p->overvoltage_warning = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->motor_loop_speed_warning =
        unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->brownout_warning = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->overcurrent_warning = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->esc_eeprom_warning = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->ext_eeprom_warning = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->sensor_warning = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->stall_warning = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->has_reset_warning = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->other_warning = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->other_sticky_fault = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->motor_type_sticky_fault = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->sensor_sticky_fault = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->can_sticky_fault = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->temperature_sticky_fault =
        unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->drv_sticky_fault = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->esc_eeprom_sticky_fault = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->firmware_sticky_fault = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->motor_startup_sticky_fault =
        unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->reserved_stickies = unpack_right_shift_u8(src_p[4], 1u, 0x3eu);
    dst_p->overvoltage_sticky_warning =
        unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->motor_loop_speed_sticky_warning =
        unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->brownout_sticky_warning = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->overcurrent_sticky_warning =
        unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->esc_eeprom_sticky_warning =
        unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->ext_eeprom_sticky_warning =
        unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->sensor_sticky_warning = unpack_right_shift_u8(src_p[5], 4u, 0x10u);
    dst_p->stall_sticky_warning = unpack_right_shift_u8(src_p[5], 5u, 0x20u);
    dst_p->has_reset_sticky_warning =
        unpack_right_shift_u8(src_p[5], 6u, 0x40u);
    dst_p->other_sticky_warning = unpack_right_shift_u8(src_p[5], 7u, 0x80u);
    dst_p->is_follower = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->reserved = unpack_right_shift_u16(src_p[6], 1u, 0xfeu);
    dst_p->reserved |= unpack_left_shift_u16(src_p[7], 7u, 0xffu);

    return (0);
}

int a301_status_1_init(a301_status_1_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_status_1_t));

    return 0;
}

uint8_t a301_status_1_other_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_other_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_other_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_motor_type_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_motor_type_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_motor_type_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_sensor_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_sensor_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_sensor_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_can_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_can_fault_decode(uint8_t value) { return ((double)value); }

bool a301_status_1_can_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_temperature_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_temperature_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_temperature_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_drv_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_drv_fault_decode(uint8_t value) { return ((double)value); }

bool a301_status_1_drv_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_esc_eeprom_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_esc_eeprom_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_esc_eeprom_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_firmware_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_firmware_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_firmware_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_motor_startup_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_motor_startup_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_motor_startup_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_reserved_actives_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_reserved_actives_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_reserved_actives_is_in_range(uint8_t value) {
    return (value <= 31u);
}

uint8_t a301_status_1_overvoltage_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_overvoltage_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_overvoltage_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_motor_loop_speed_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_motor_loop_speed_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_motor_loop_speed_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_brownout_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_brownout_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_brownout_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_overcurrent_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_overcurrent_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_overcurrent_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_esc_eeprom_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_esc_eeprom_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_esc_eeprom_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_ext_eeprom_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_ext_eeprom_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_ext_eeprom_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_sensor_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_sensor_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_sensor_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_stall_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_stall_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_stall_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_has_reset_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_has_reset_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_has_reset_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_other_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_other_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_other_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_other_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_other_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_other_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_motor_type_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_motor_type_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_motor_type_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_sensor_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_sensor_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_sensor_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_can_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_can_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_can_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_temperature_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_temperature_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_temperature_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_drv_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_drv_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_drv_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_esc_eeprom_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_esc_eeprom_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_esc_eeprom_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_firmware_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_firmware_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_firmware_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_motor_startup_sticky_fault_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_motor_startup_sticky_fault_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_motor_startup_sticky_fault_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_reserved_stickies_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_reserved_stickies_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_reserved_stickies_is_in_range(uint8_t value) {
    return (value <= 31u);
}

uint8_t a301_status_1_overvoltage_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_overvoltage_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_overvoltage_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_motor_loop_speed_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_motor_loop_speed_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_motor_loop_speed_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_brownout_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_brownout_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_brownout_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_overcurrent_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_overcurrent_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_overcurrent_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_esc_eeprom_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_esc_eeprom_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_esc_eeprom_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_ext_eeprom_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_ext_eeprom_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_ext_eeprom_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_sensor_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_sensor_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_sensor_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_stall_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_stall_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_stall_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_has_reset_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_has_reset_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_has_reset_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_other_sticky_warning_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_other_sticky_warning_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_other_sticky_warning_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint8_t a301_status_1_is_follower_encode(double value) {
    return (uint8_t)(value);
}

double a301_status_1_is_follower_decode(uint8_t value) {
    return ((double)value);
}

bool a301_status_1_is_follower_is_in_range(uint8_t value) {
    return (value <= 1u);
}

uint16_t a301_status_1_reserved_encode(double value) {
    return (uint16_t)(value);
}

double a301_status_1_reserved_decode(uint16_t value) { return ((double)value); }

bool a301_status_1_reserved_is_in_range(uint16_t value) {
    return (value <= 32767u);
}

int a301_status_2_pack(uint8_t *dst_p, const a301_status_2_t *src_p,
                       size_t size) {
    uint32_t encoder_velocity;
    uint32_t relative_encoder_position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&encoder_velocity, &src_p->encoder_velocity,
           sizeof(encoder_velocity));
    dst_p[0] |= pack_left_shift_u32(encoder_velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(encoder_velocity, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(encoder_velocity, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(encoder_velocity, 24u, 0xffu);
    memcpy(&relative_encoder_position, &src_p->relative_encoder_position,
           sizeof(relative_encoder_position));
    dst_p[4] |= pack_left_shift_u32(relative_encoder_position, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(relative_encoder_position, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(relative_encoder_position, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(relative_encoder_position, 24u, 0xffu);

    return (8);
}

int a301_status_2_unpack(a301_status_2_t *dst_p, const uint8_t *src_p,
                         size_t size) {
    uint32_t encoder_velocity;
    uint32_t relative_encoder_position;

    if (size < 8u) {
        return (-EINVAL);
    }

    encoder_velocity = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    encoder_velocity |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    encoder_velocity |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    encoder_velocity |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->encoder_velocity, &encoder_velocity,
           sizeof(dst_p->encoder_velocity));
    relative_encoder_position = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    relative_encoder_position |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    relative_encoder_position |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    relative_encoder_position |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->relative_encoder_position, &relative_encoder_position,
           sizeof(dst_p->relative_encoder_position));

    return (0);
}

int a301_status_2_init(a301_status_2_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_status_2_t));

    return 0;
}

float a301_status_2_encoder_velocity_encode(double value) {
    return (float)(value);
}

double a301_status_2_encoder_velocity_decode(float value) {
    return ((double)value);
}

bool a301_status_2_encoder_velocity_is_in_range(float value) {
    (void)value;

    return (true);
}

float a301_status_2_relative_encoder_position_encode(double value) {
    return (float)(value);
}

double a301_status_2_relative_encoder_position_decode(float value) {
    return ((double)value);
}

bool a301_status_2_relative_encoder_position_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_status_3_pack(uint8_t *dst_p, const a301_status_3_t *src_p,
                       size_t size) {
    uint32_t absolute_encoder_position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->reserved, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->reserved, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->reserved, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->reserved, 24u, 0xffu);
    memcpy(&absolute_encoder_position, &src_p->absolute_encoder_position,
           sizeof(absolute_encoder_position));
    dst_p[4] |= pack_left_shift_u32(absolute_encoder_position, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(absolute_encoder_position, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(absolute_encoder_position, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(absolute_encoder_position, 24u, 0xffu);

    return (8);
}

int a301_status_3_unpack(a301_status_3_t *dst_p, const uint8_t *src_p,
                         size_t size) {
    uint32_t absolute_encoder_position;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->reserved = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->reserved |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    absolute_encoder_position = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    absolute_encoder_position |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    absolute_encoder_position |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    absolute_encoder_position |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->absolute_encoder_position, &absolute_encoder_position,
           sizeof(dst_p->absolute_encoder_position));

    return (0);
}

int a301_status_3_init(a301_status_3_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_status_3_t));

    return 0;
}

uint32_t a301_status_3_reserved_encode(double value) {
    return (uint32_t)(value);
}

double a301_status_3_reserved_decode(uint32_t value) { return ((double)value); }

bool a301_status_3_reserved_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}

float a301_status_3_absolute_encoder_position_encode(double value) {
    return (float)(value);
}

double a301_status_3_absolute_encoder_position_decode(float value) {
    return ((double)value);
}

bool a301_status_3_absolute_encoder_position_is_in_range(float value) {
    (void)value;

    return (true);
}

int a301_unique_id_broadcast_pack(uint8_t *dst_p,
                                  const a301_unique_id_broadcast_t *src_p,
                                  size_t size) {
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u32(src_p->unique_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->unique_id, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->unique_id, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->unique_id, 24u, 0xffu);

    return (4);
}

int a301_unique_id_broadcast_unpack(a301_unique_id_broadcast_t *dst_p,
                                    const uint8_t *src_p, size_t size) {
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->unique_id = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->unique_id |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->unique_id |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->unique_id |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

int a301_unique_id_broadcast_init(a301_unique_id_broadcast_t *msg_p) {
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(a301_unique_id_broadcast_t));

    return 0;
}

uint32_t a301_unique_id_broadcast_unique_id_encode(double value) {
    return (uint32_t)(value);
}

double a301_unique_id_broadcast_unique_id_decode(uint32_t value) {
    return ((double)value);
}

bool a301_unique_id_broadcast_unique_id_is_in_range(uint32_t value) {
    (void)value;

    return (true);
}
